eMarket/cart/urls.py
from django.urls import path
from . import views

app_name = "cart"

urlpatterns = [
    path("", views.cart_detail, name="cart_detail"),
    path("add/<uuid:product_id>/", views.cart_add, name="cart_add"),
    path("remove/<uuid:product_id>/", views.cart_remove, name="cart_remove"),
]

eMarket/eMarket/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("cart/", include("cart.urls", namespace="cart")),
    path("orders/", include("orders.urls", namespace="orders")),
    path("", include("market.urls", namespace="market")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eMarket/market/urls.py
from django.urls import path
from . import views

app_name = "market"

urlpatterns = [
    path("", views.product_list, name="product_list"),
    path(
        "<slug:category_identifier>/",
        views.product_list,
        name="product_list_by_category",
    ),
    path("<uuid:id>/<slug:identifier>/", views.product_detail, name="product_detail"),
]

eMarket/orders/urls.py
from django.urls import path
from . import views

app_name = "orders"

urlpatterns = [
    path("create/", views.create_order, name="create_order"),
]

eMarket/cart/models.py
from django.db import models

# Create your models here.

eMarket/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 11)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update_quantity = forms.BooleanField(
        required=False, initial=False, widget=forms.HiddenInput
    )

eMarket/cart/views.py
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from market.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    """
    Add a product to the cart or update its quantity.

    Args:
        request (HttpRequest): The request object.
        product_id (int): The product ID.
    Returns:
        HttpResponseRedirect: The cart detail page.
    """
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)

    if form.is_valid():
        cleaned_data = form.cleaned_data
        cart.add(
            product=product,
            quantity=cleaned_data["quantity"],
            update_quantity=cleaned_data["update_quantity"],
        )

    # messages.success(request, f"Added {product.name} to your cart.")

    return redirect("cart:cart_detail")


@require_POST
def cart_remove(request, product_id):
    """
    Remove a product from the cart.

    Args:
        request (HttpRequest): The request object.
        product_id (int): The product ID.
    Returns:
        HttpResponseRedirect: The cart detail page.
    """
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)

    return redirect("cart:cart_detail")


def cart_detail(request):
    """
    Display all items in the cart.

    Args:
        request (HttpRequest): The request object.
    Returns:
        HttpResponse: The response object.
    """

    cart = Cart(request)
    # return render(request, "cart/detail.html", {"cart": cart})

    # for item in cart:
    #     item["update_quantity_form"] = CartAddProductForm(
    #         initial={"quantity": item["quantity"]}
    #     )

    for item in cart:
        item["update_quantity_form"] = CartAddProductForm(
            initial={"quantity": item["quantity"], "update_quantity": True}
        )

    return render(request, "cart/detail.html", {"cart": cart})

eMarket/cart/templates/cart/detail.html
{% extends "market/layout.html" %}
{% load static %}

{% block title %}
Your shopping cart
{% endblock %}

{% block content %}

{% if cart %}
<h1>Your shopping cart</h1>

<table class="cart">
	<thead>
		<tr>
			<th>Image</th>
			<th>Product</th>
			<th>Quantity</th>
			<th>Remove</th>
			<th>Unit price</th>
			<th>Price</th>
		</tr>
	</thead>
	<tbody>
		{% for item in cart %}
		{% with product=item.product %}
		<tr>
			<td>
				<a href="{{ product.get_absolute_url }}">
					<img src="{{ product.image.url }}">
				</a>
			</td>
			<td>{{ product.name }}</td>
			<td>
				<form action="{% url 'cart:cart_add' product.id %}" method="post">
					{{ item.update_quantity_form.quantity }}
					{{ item.update_quantity_form.update_quantity }}
					<input type="submit" value="Update">
					{% csrf_token %}
				</form>
			</td>
			<td>
				<form action="{% url 'cart:cart_remove' product.id %}" method="post">
					<input type="submit" value="Remove">
					{% csrf_token %}
				</form>
			</td>
			<td class="num">Ksh{{ item.price }}</td>
			<td class="num">Ksh{{ item.total_price }}</td>
		</tr>
		{% endwith %}
		{% endfor %}
		<tr class="total">
			<td>Total</td>
			<td colspan="4"></td>
			<td class="num">Ksh{{ cart.get_total_price }}</td>
		</tr>
	</tbody>
</table>

<p class="text-right"><a href="{% url 'orders:create_order' %}" class="button">Checkout</a></p>
{% else %}
<h1>Your shopping cart is empty</h1>
{% endif %}
<p>
	<a href="{% url 'market:product_list' %}" class="button">Continue shopping</a>
</p>

{% endblock %}